- bower.json
Downgrade iron-validatable-behavior to 1.x
Note: Must manually add a resolution if 2.x is wanted
> Downgrade iron-validatable-behavior to 1.x

- cosmoz-autocomplete.js
- lib/use-autocomplete.js
- package-lock.json
- stories/cosmoz-autocomplete.stories.js
Multiple text state updates in cosmoz-autocomplete on clear are to quick for `lit-virtualizer` to handle and it does not manage to cleanup old items.
This PR fixes it.
> Fixes multiple text state updates on clear

- lib/use-select.js
If limit is 1 extract value from array to call onSelect with `value` instead of `[value]`.
> fix: unarray value on select if limit is 1

- lib/use-suggestions.js
- test/cosmoz-suggestions.test.js
- test/use-suggestions.test.js
In cosmoz-autocomplete we currently reset the selection `index` to undefined whenever `items` changes.
It makes more sense to reset the selection to '0' instead to allow the user to quickly highlight the first item (because query helps to remove unwanted items) and press `Enter` to select.
> feat: when items or query changes reset index to 0 instead of undefined

- lib/use-autocomplete.js
Add events for `text` and `value` state changes.
Useful when we need to use that instead of onText, onChange props.
> fix: add text and value events

- lib/autocomplete.js
- lib/use-suggestions.js
Instead of using the full `cosmoz-autocomplete` element as anchor for
suggestions use the input element instead. This fixes misc issues in frontend
and allows to use suggestions for other inputs too.
> fix: use input as anchor for suggestions

- lib/use-keyboard.js
- lib/use-suggestions.js
- package-lock.json
- package.json
Reduce the amount of added and removed event listeners by only
adding one when attached and removing it on detach
> refactor: add only one listener on attach for use-keyboard

- lib/autocomplete.js
- lib/use-autocomplete.js
- test/use-autocomplete.test.js
`source` can now be promise or a function that returns promise that
is called with `active` (`!disabled` and `focused` ) and `query` (trimmed text).
If `source` is a Promise than a spinner is shown when pending and any errors
are caught and passed to `cosmoz-input` to be displayed (invalid, error-message).
Fixes #96
Example usage: 
```
<cosmoz-autocomplete 
text-property="label" 
external
.source=${ debounce(({query})=> fetch(`api/items?query=${query}`).then((r)=>r.json())) }
><cosmoz-autocomplete>
```
> feat(autocomplete): support function and/or Promise source

- lib/autocomplete.css.js
Removes the max width when displaying one chip in multi mode.
> fix(autocomplete): remove one chip max-width

- src/autocomplete/chip.css.ts
Bug [AB#10800](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/10800) - chips' minimum dimension caused overlap with other omnitable headers. This PR should fix it reducing their minimum size.
> fix: chips no longer hovering other omnitable fields

- .eslintignore
- .github/workflows/preview.yml
- .gitignore
- stories/cosmoz-autocomplete.stories.js
> feat: preview prs

- package-lock.json
- package.json
About Feature [AB#11519](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/11519) - latest `cosmoz-input` release (v5.0.0) needs to be installed in all the components using it.
> fix(dependencies): newest cosmoz input needed in this repo

- src/listbox/index.ts
- src/listbox/style.css.ts
- stories/cosmoz-autocomplete.stories.js
- stories/data.js
- Fix the listbox `.items { min-height: 150px }` issue
- Remove the unneeded popover padding
- Add storybook story to test out the fix for listbox
> Fix the listbox `min-height` issue and remove the popover padding

- src/autocomplete/autocomplete.ts
- test/__snapshots__/cosmoz-autocomplete.test.snap.js
Export input part 'wrap' to prevent autocomplete chip text overflow in cz-accounting.
[AB#11348](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/11348/)
> fix(cosmoz-autocomplete): export part wrap

- src/listbox/style.css.ts
Fix the vertical scroll to take exactly the height of the items, not more.
Brief explanation: Virtualizer is based on the fact that `virtualizer-sizer` elements have a height of 2px.
When the `virtualizer-sizer` element has a `line-height` greater than 1 it adds the possibility of creating an overflow and then the vertical scroll doesn't match the height of the elements, it's bigger.
> fix: make the sizer take no height

- src/autocomplete/skeleton-span.ts
> fix: loader looks bad on very narrow inputs

- src/listbox/style.css.ts
Makes sure the dropdown doesn't show up when there's no value. 
Before:
After:
> fix: don't show listbox dropdown when there's no value

- src/autocomplete/autocomplete.ts
- src/listbox/index.ts
- src/listbox/item-renderer.ts
- src/listbox/style.css.ts
- src/listbox/use-item-height.ts
- src/listbox/use-listbox.ts
- src/listbox/use-render-item.ts
- test/cosmoz-listbox.test.js
When `itemHeight` is set to `'auto'`, it will let the virtualizer calculate the height of the children. Useful when you have a custom item renderer with variable height.
Also did some cleanup, more details in the commit log.
> feat: support for item-height="auto" 

- src/autocomplete/autocomplete.ts
If you have a custom renderer with a button, for example, tabbing to it closes the listbox.
Solution: move the focus tracking to the host element (cosmoz-autocomplete). Focusing inside the listbox will keep it open.
> fix: listbox closes when focus moves into it

- src/listbox/index.ts
Adding margin to custom results makes the scrollbar show when it shouldn't.
> fix: margin is not taken into account when item-size="auto"

- src/autocomplete/autocomplete.ts
If you focus an autocomplete element that has an empty array as it's source, then listbox is rapidly created and removed (during the source$ promise handling) causing the useKeyboard effect to initialize *after* the element has been removed from DOM, leading to a phantom keydown event handler that is never cleared.
Fixes https://neovici.slack.com/archives/C6LJQMJFM/p1757426096769989
Reported upstream https://github.com/pionjs/pion/issues/64
> fix: keyboard navigation stops working
