cosmoz-autocomplete.html

Requesting review on this in order to merge into master.

Replacing content with slot. Refs #15934

---

bower.json
demo/index.html
demo/items.json

Demo page was redone using iron-demo-helpers element (recommended element to create demo pages).
At present demo-snippet element doesn't show source code (because of this issue - https://github.com/PolymerElements/iron-demo-helpers/issues/29).
Hope this issue will be fixed soon (or I'll find workaround). Anyway it provides good looking Polymer style demo page.

Code clearing (+ small fixes/refactoring), using iron-demo-helpers component

---

cosmoz-autocomplete.html

Fixed issue #3 "required attribute not supported"

Issue #3 fix

---

.eslintrc.json
cosmoz-autocomplete.js
package-lock.json
package.json
test/.eslintrc
test/cosmoz-autocomplete_test.html

Update ESLint rules

---

.travis.yml
package-lock.json
package.json

Use node 6.x on travis-ci and upgrade polymer cli

Use node 6.x on travis-ci

---

cosmoz-autocomplete.js
cosmoz-suggestions.js
lib/use-autocomplete.js
lib/utils.js
test/cosmoz-suggestions.test.js

feat: adds query mark to cosmoz-suggestions

---

lib/utils.js
package-lock.json
package.json

Fixes `prop` utility function when key is falsy.
Fixes `@open-wc/demoing-storybook` in prod dependencies.
`package-lock` updates

fix: prop should fallback to identity if key is falsy

---

cosmoz-suggestions.js
lib/autocomplete.js

Adds suggestionsWidth property to control suggestions width when need
Tweaks suggestion items styling

fix: adds suggestionsWidth property

---

cosmoz-suggestions.js
lib/use-autocomplete.js
lib/use-suggestions.js
test/use-autocomplete.test.js

`external` attribute will show the query in completions but it
will not search using it
auto sizing behavior has been moved to useAutosize
Added a limit param to control the number of rendered suggestions

fix: improves autosize and external behavior

---

__snapshots__/cosmoz-autocomplete-ui.md
__snapshots__/cosmoz-autocomplete.md
lib/autocomplete.js

fix(autocomplete): better ui for single selection

---

lib/use-suggestions.js
test/use-suggestions.test.js

fix(suggestions): handles onEnter without highlight/selection

---

__snapshots__/cosmoz-autocomplete-ui.md
__snapshots__/cosmoz-autocomplete.md
cosmoz-suggestions.js
lib/autocomplete.js
lib/use-autocomplete.js
package-lock.json
package.json
shell.nix
tsconfig.json

Fixes #62 
Adds typescript and some basic setting in tsconfig.json

Hide completions on disabled focus

---

lib/utils.js
package-lock.json
package.json
test/utils.test.js

use functional utils from @neovici/cosmoz-utils

fix: use functional utils from @neovici/cosmoz-utils

---

cosmoz-autocomplete.js
package-lock.json
package.json

`cosmoz-autocomplete` now sets it's `value` and `text` properties instead of internal state on update.

fix: change state to props to fix changed events

---

lib/autocomplete.js
lib/use-backspace.js

Use correct limit is one check

fix: correct limit is one check

---

lib/autocomplete.js
lib/use-suggestions.js
stories/cosmoz-autocomplete.stories.js

Adds support for a defaultIndex which set the index that will be used
by default for the highlight of suggestions

feat(suggesions): add support for default-index(defaultIndex)

---

lib/autocomplete.js
lib/use-suggestions.js

Improve default-index parsing
Reset to 1 if we have less that 2 items.

fix: improve default-index

---

__snapshots__/cosmoz-autocomplete-ui.md
__snapshots__/cosmoz-autocomplete.md
lib/autocomplete.js

Export line and error parts from input component
Use own observedAttributes

fix: export line and error parts from input

---

cosmoz-listbox.js
lib/item-renderer.js
lib/use-listbox.js
lib/utils.js
package-lock.json

- chore(deps): upgrade
- fix(listbox): improve scrolling and selection

 fix(listbox): improve scrolling and selection

---

lib/use-focus.js

feat(use-focus): add onToggle

---

.github/workflows/ci.yml
cosmoz-listbox.js
package-lock.json
package.json

Fixes white-space at the end of the list if line-height is more than 1.

fix(cosmoz-listbox): fix white-space at the end of the list

---

cosmoz-listbox.js
lib/autocomplete.css.js

fix(listbox): better auto sizing

---

lib/autocomplete.css.js
lib/autocomplete.js
package-lock.json
test/cosmoz-autocomplete.test.js

Show one chip when using multi selection and there is one item selected.

fix(autocomplete): show one chip

---

cosmoz-listbox.js

Correctly display the svg check mark.

fix(listbox): display the svg check mark

---

lib/autocomplete.css.js
lib/autocomplete.js
test/cosmoz-autocomplete.test.js

Add clear button in badge to clear the value.

feat(autocomplete): add badge clear

---

cosmoz-listbox.js
lib/autocomplete.js
lib/item-renderer.js
lib/use-listbox.js
package-lock.json
package.json

Allow composing the item rendering to display data in different ways.

feat: allow composing item renderer

---

lib/use-autocomplete.js

Get correct `keep-opened` from props.

fix(autocomplete): get keep-opened from props

---

lib/item-renderer.js

Measure the whole rendered content and only the item's text.

fix(item-renderer): measure the rendered content

---

lib/autocomplete.css.js

Prevent autocomplete spinner from flexing.

fix(autocomplete): prevent autocomplete spinner from flexing

---

lib/autocomplete.css.js

Add more css vars to style autocomplete chips.

feat(autocomplete): add more css vars to style chips

---

cosmoz-listbox.js

memoize virtualizer layout config

fix(listbox): memoize virtualizer layout config

---

package-lock.json
src/autocomplete/use-autocomplete.ts

feat: update ts

---

src/autocomplete/use-autocomplete.ts

feat(textual): configurable autocomplete textual

---

.eslintignore
package-lock.json
src/autocomplete/autocomplete.ts
src/autocomplete/chip.css.ts
src/autocomplete/chip.ts
src/autocomplete/selection.ts
src/autocomplete/styles.css.ts
src/autocomplete/use-autocomplete.ts
src/autocomplete/use-overflow.ts
src/autocomplete/util.ts
stories/cosmoz-autocomplete.stories.js
test/__snapshots__/cosmoz-autocomplete.test.snap.js
test/cosmoz-autocomplete.test.js

BREAKING CHANGE:
Show multiple chips on the same rows before input.
Collapse chips that don't fit into a numbered badge.

feat(autocomplete): multiple chips

---

package-lock.json
src/autocomplete/autocomplete.ts
src/autocomplete/styles.css.ts
test/__snapshots__/cosmoz-autocomplete.test.snap.js
test/cosmoz-autocomplete.test.js

Hide input only when autocomplete has a single value.

feat(input): hide input only when single

---

src/autocomplete/autocomplete.ts
test/__snapshots__/cosmoz-autocomplete.test.snap.js

feat(input): export input's control part

---

src/autocomplete/chip.css.ts

Reverts Neovici/cosmoz-autocomplete#140

Revert "fix: chips no longer hovering other omnitable fields"

---

src/autocomplete/autocomplete.ts

Re https://neovici.slack.com/archives/CCU2R1Q3Y/p1686840722339209?thread_ts=1686832901.319889&cid=CCU2R1Q3Y

fix: value-property attribute is not observed

---

src/autocomplete/use-autocomplete.ts
src/autocomplete/util.ts
test/use-autocomplete.test.js

Maintain query case. 
Do not automatically convert to lower case.

feat(autocomplete): maintain query case

---

src/listbox/style.css.ts

Hide item overflow as it will be set sizer.

feat(listbox): hide item overflow

---

package-lock.json
package.json
src/autocomplete/use-autocomplete.ts
src/autocomplete/util.ts

When source function returns false or null map that to an empty array.

feat(autocomplete): handle falsy source

---

package-lock.json
src/autocomplete/autocomplete.ts
src/autocomplete/chip.css.ts
src/autocomplete/chip.ts
src/autocomplete/index.ts
src/autocomplete/selection.ts
src/autocomplete/use-autocomplete.ts
src/listbox/index.ts
src/listbox/style.css.ts
stories/cosmoz-autocomplete.stories.js

Added modifiers: 
* preserve-order - don't sort selected values to the top of the list
* min - prevent deselection via listbox or chip when minimum number of selected values is reached
Also moved away from style tags, using adopted stylesheets everywhere.

Modifiers to act more like select

---

package-lock.json
package.json
src/listbox/index.ts
src/listbox/style.css.ts
test/cosmoz-autocomplete.test.js

Use popover for `<cosmoz-listbox>` component in Chrome (because only Chrome supports popover) and fallback to `portal` in Firefox

Use popover for `<cosmoz-listbox>` component

---

src/autocomplete/chip.css.ts

Add css var to have possibility to hide clear icon in cosmoz-autocomplete

feat(cosmoz-autocomplete): add css var to hide clear icon

---

test/__snapshots__/cosmoz-autocomplete.test.snap.js

The tests did not register the assertionError correctly, needs investigating.

test: updated snapshots

---

src/listbox/style.css.ts
stories/cosmoz-autocomplete.stories.js

Fix `text-transform: uppercase` for listbox values

Fix `text-transform: uppercase` for listbox values

---

package-lock.json
package.json

Re https://github.com/semantic-release/release-notes-generator/issues/655

build: release process is failing

---

CHANGELOG.md
package-lock.json
package.json
src/listbox/style.css.ts

Adds some variables needed for themes and refines styling somewhat.

feat: add variables and improve styling

---

src/autocomplete/chip.css.ts
src/autocomplete/use-keys.ts
src/listbox/style.css.ts
test/__snapshots__/cosmoz-autocomplete.test.snap.js
test/use-keys.test.js

* Some styling tweaks
* Also added a setting that prevents users from clearing the input with backspace when a value must be selected

feat: labels styling

---

src/autocomplete/autocomplete.ts
src/listbox/style.css.ts

[vokoscreenNG-2025-08-28_01-00-42.webm](https://github.com/user-attachments/assets/daf3d098-0f5d-4a14-bdd9-5f4759b7a92b)

feat: opening animation

---

src/autocomplete/autocomplete.ts
src/autocomplete/use-autocomplete.ts

Reify loading state, improve conditions to display the dropdown

fix: dropdown is not displayed while the source is loading

---

src/listbox/item-renderer.ts
src/listbox/use-listbox.ts

This is useful for implementing autocomplete with cz-preview support

feat: itemRenderer can access the items list

---

src/listbox/style.css.ts

Reduces the opacity for the listbox a little bit.
https://neovici.slack.com/archives/C0APSNTPB/p1756195707406189

feat: adjust opacity for listbox

---

src/autocomplete/autocomplete.ts
src/autocomplete/use-autocomplete.ts
src/autocomplete/use-overflow.ts
src/autocomplete/util.ts
src/listbox/item-renderer.ts
src/listbox/use-listbox.ts
src/listbox/util.ts

The typing was wrong: `text` can be `undefined`. Fixed typing and added necessary checks.
Fixes https://neovici.slack.com/archives/C6LJQMJFM/p1757406508549769

fix: fatal error when text is undefined
